CREATE TABLE IF NOT EXISTS article
(
    id            bigint AUTO_INCREMENT COMMENT 'id' PRIMARY KEY,
    taskId        varchar(64)                           NOT NULL COMMENT '任务ID（UUID）',
    userId        bigint                                NOT NULL COMMENT '用户ID',
    topic         varchar(500)                          NOT NULL COMMENT '选题',
    mainTitle     varchar(200)                          NULL COMMENT '主标题',
    subTitle      varchar(300)                          NULL COMMENT '副标题',
    outline       json                                  NULL COMMENT '大纲（JSON格式）',
    content       text                                  NULL COMMENT '正文（Markdown格式）',
    fullContent   text                                  NULL COMMENT '完整图文（Markdown格式，含配图）',
    coverImage    varchar(512)                          NULL COMMENT '封面图 URL',
    images        json                                  NULL COMMENT '配图列表（JSON数组）',
    status        varchar(20) DEFAULT 'PENDING'         NOT NULL COMMENT '状态：PENDING/PROCESSING/COMPLETED/FAILED',
    errorMessage  text                                  NULL COMMENT '错误信息',
    createTime    datetime    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    completedTime datetime                              NULL COMMENT '完成时间',
    updateTime    datetime    DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    isDelete      tinyint     DEFAULT 0                 NOT NULL COMMENT '是否删除',
    UNIQUE KEY uk_taskId (taskId),
    INDEX idx_userId (userId),
    INDEX idx_status (status),
    INDEX idx_createTime (createTime),
    INDEX idx_userId_status (userId, status)
) COMMENT '文章表' COLLATE = utf8mb4_unicode_ci;
